version: "3.8"

services:
  api:
    build:
      context: ./BackendCloudArch
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./FrontendCloudArch
    ports:
      - "42001:42001"
    depends_on:
      - api

volumes:
  mongo-data:
